name: Docker Publish (Beta Images)

on:
  # When changes are pushed to the "dev" branch, run it
  push:
    branches:
      - dev

  # Run every week at 0800 UTC to update the images
  schedule:
    - cron: '0 8 * * 1'

env:
  DOCKER_IMAGE_PREFIX: "beta-"

jobs:
  build-cli:
    uses: ./.github/workflows/workflow-docker-publish.yml
    with:
      upstream-channel-prefix: 'beta-'
      tag-prefix: "$DOCKER_IMAGE_PREFIX"
      php-variation: cli
    secrets: inherit

  build-fpm:
    uses: ./.github/workflows/workflow-docker-publish.yml
    with:
      upstream-channel-prefix: 'beta-'
      tag-prefix: "$DOCKER_IMAGE_PREFIX"
      php-variation: fpm
    secrets: inherit

  build-fpm-nginx:
    uses: ./.github/workflows/workflow-docker-publish.yml
    with:
      upstream-channel-prefix: 'beta-'
      tag-prefix: "$DOCKER_IMAGE_PREFIX"
      php-variation: fpm-nginx
    secrets: inherit

  build-fpm-apache:
    uses: ./.github/workflows/workflow-docker-publish.yml
    with:
      upstream-channel-prefix: 'beta-'
      tag-prefix: "$DOCKER_IMAGE_PREFIX"
      php-variation: fpm-nginx
    secrets: inherit