name: Docker Publish (Beta Images)

on:
  # When changes are pushed to the "dev" branch, run it
  push:
    branches:
      - dev

  # Run every week at 0800 UTC to update the images
  schedule:
    - cron: '0 8 * * 1'

jobs:
  push:
    runs-on: ubuntu-20.04

    # Configure our deployment strategy. Order is important here and we want it to go: CLI < FPM < FPM-NGINX
    strategy:
      # We want to limit the number of jobs to the number of versions that we're offering (since we want the dependency order to be built correctly)
      max-parallel: 3
      # Set our base image and versions here
      matrix:
        php-variation:
          - cli
          - fpm
          - fpm-nginx
          - fpm-apache
        php-version: 
          - "7.4"
          - "8.0"
          - "8.1"

    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            UPSTREAM_CHANNEL=beta-
          context: generated-dockerfiles/${{ matrix.php-version }}/${{ matrix.php-variation }}/.
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64/v8
          pull: true
          push: true
          tags: serversideup/php:beta-${{ matrix.php-version }}-${{ matrix.php-variation }}

  ##################################################
  # Commenting this out until further notice
  ##################################################
  # trigger_downstream_jobs:
  #   needs: push
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Trigger downstream builds
  #       run: curl --fail --output "/dev/null" --silent --show-error -X POST -F token=${{ secrets.DOWNSTREAM_BUILD_TOKEN }} -F ref=$GITHUB_REF ${{ secrets.DOWNSTREAM_BUILD_WEBHOOK_ENDPOINT }}
