name: Docker Publish (Beta Images)

on:
  # When changes are pushed to the "dev" branch, run it
  push:
    branches:
      - dev

  # Run every week at 0800 UTC to update the images
  schedule:
    - cron: '0 8 * * 1'

env:
  DOCKER_IMAGE_PREFIX: "beta-"
  UPSTREAM_CHANNEL_PREFIX: "beta-"

jobs:
  cli:
    uses: ./.github/workflows/workflow-docker-publish.yml
    with:
      upstream-channel-prefix: "${UPSTREAM_CHANNEL_PREFIX}"
      tag-prefix: "${DOCKER_IMAGE_PREFIX}"
      php-variation: cli
    secrets: inherit

  fpm:
    needs: cli
    uses: ./.github/workflows/workflow-docker-publish.yml
    with:
      upstream-channel-prefix: "${UPSTREAM_CHANNEL_PREFIX}"
      tag-prefix: "${DOCKER_IMAGE_PREFIX}"
      php-variation: fpm
    secrets: inherit

  fpm-nginx:
    needs: fpm
    uses: ./.github/workflows/workflow-docker-publish.yml
    with:
      upstream-channel-prefix: "${UPSTREAM_CHANNEL_PREFIX}"
      tag-prefix: "${DOCKER_IMAGE_PREFIX}"
      php-variation: fpm-nginx
    secrets: inherit

  fpm-apache:
    needs: fpm
    uses: ./.github/workflows/workflow-docker-publish.yml
    with:
      upstream-channel-prefix: "${UPSTREAM_CHANNEL_PREFIX}"
      tag-prefix: "${DOCKER_IMAGE_PREFIX}"
      php-variation: fpm-nginx
    secrets: inherit