on:
  workflow_call:
    inputs:
      upstream-channel-prefix:
        required: true
        type: string
        default: ''
      base-ubuntu-version:
        required: true
        type: string
        default: '20.04'
      tag-prefix:
        required: true
        type: string
        default: 'beta-'

jobs:
  docker-publish:
    runs-on: ubuntu-20.04

   # Configure our deployment strategy. Order is important here and we want it to go: CLI < FPM < FPM-NGINX
    strategy:
      # We want to limit the number of jobs to the number of versions that we're offering (since we want the dependency order to be built correctly)
      max-parallel: 3
      # Set our base image and versions here
      matrix:
        php-variation:
          - cli
          - fpm
          - fpm-nginx
          - fpm-apache
        php-version: 
          - "7.4"
          - "8.0"
          - "8.1"

    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2

      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.branch-name.outputs.current_branch }}

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            UPSTREAM_CHANNEL=${{ inputs.upstream-channel-prefix }}
            BASE_UBUNTU_VERSION=${{ inputs.base-ubuntu-version }}
          context: dist/${{ matrix.php-version }}/${{ matrix.php-variation }}/.
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64/v8
          pull: true
          push: true
          tags: serversideup/php:${{ inputs.tag-prefix}}${{ matrix.php-version }}-${{ matrix.php-variation }}